"""
sources/epg/epg_xmltv_parser.py
================================
Parses XMLTV guide.xml output from iptv-org/epg and extracts
EPL and UCL football fixtures with their confirmed channel assignments.

This replaces most HTML scrapers with a single structured data source.

Usage:
    from sources.epg.epg_xmltv_parser import parse_guide
    fixtures = parse_guide("guide.xml", days_ahead=30)

The guide.xml is generated by running:
    npm run grab --- --channels epg_channels.xml --output guide.xml
    
inside a clone of https://github.com/iptv-org/epg
"""

import xml.etree.ElementTree as ET
import re
import logging
from datetime import datetime, date, timezone, timedelta
from typing import Optional

logger = logging.getLogger(__name__)

# ── Channel ID → broadcaster metadata ──────────────────────────────────────
# Maps xmltv_id → { broadcaster, country, region, type, icon }
CHANNEL_MAP = {
    # UK — TNT Sports
    "TNTSports1.uk@SD":             {"broadcaster": "TNT Sports",        "country": "United Kingdom",       "channels": "TNT Sports 1",                    "type": "tv",     "icon": "📺"},
    "TNTSports2.uk@SD":             {"broadcaster": "TNT Sports",        "country": "United Kingdom",       "channels": "TNT Sports 2",                    "type": "tv",     "icon": "📺"},
    "TNTSports4.uk@SD":             {"broadcaster": "TNT Sports",        "country": "United Kingdom",       "channels": "TNT Sports 4",                    "type": "tv",     "icon": "📺"},
    # UK — Sky Sports
    "SkySportsMainEvent.uk@SD":     {"broadcaster": "Sky Sports",        "country": "United Kingdom",       "channels": "Sky Sports Main Event",           "type": "tv",     "icon": "📺"},
    "SkySportsPremierLeague.uk@SD": {"broadcaster": "Sky Sports",        "country": "United Kingdom",       "channels": "Sky Sports Premier League",       "type": "tv",     "icon": "📺"},
    "SkySportsFootball.uk@SD":      {"broadcaster": "Sky Sports",        "country": "United Kingdom",       "channels": "Sky Sports Football",             "type": "tv",     "icon": "📺"},
    "SkySportsAction.uk@SD":        {"broadcaster": "Sky Sports",        "country": "United Kingdom",       "channels": "Sky Sports Action",               "type": "tv",     "icon": "📺"},
    "SkySports4K.uk@UHD":           {"broadcaster": "Sky Sports",        "country": "United Kingdom",       "channels": "Sky Sports Ultra HDR",            "type": "tv",     "icon": "📺"},
    # UK — Free to air
    "BBCOne.uk@SD":                 {"broadcaster": "BBC Sport",         "country": "United Kingdom",       "channels": "BBC One",                         "type": "free",   "icon": "📡", "highlights_only": True},
    "BBCTwo.uk@SD":                 {"broadcaster": "BBC Sport",         "country": "United Kingdom",       "channels": "BBC Two",                         "type": "free",   "icon": "📡", "highlights_only": True},
    # MENA — beIN Sports
    "beINSports1.qa@MENA":          {"broadcaster": "beIN Sports",       "country": "Middle East & North Africa", "channels": "beIN Sports HD 1",          "type": "tv",     "icon": "📺"},
    "beINSports2.qa@MENA":          {"broadcaster": "beIN Sports",       "country": "Middle East & North Africa", "channels": "beIN Sports HD 2",          "type": "tv",     "icon": "📺"},
    "beINSports3.qa@MENA":          {"broadcaster": "beIN Sports",       "country": "Middle East & North Africa", "channels": "beIN Sports HD 3",          "type": "tv",     "icon": "📺"},
    "beINSports4.qa@MENA":          {"broadcaster": "beIN Sports",       "country": "Middle East & North Africa", "channels": "beIN Sports HD 4",          "type": "tv",     "icon": "📺"},
    "beINSports5.qa@MENA":          {"broadcaster": "beIN Sports",       "country": "Middle East & North Africa", "channels": "beIN Sports HD 5",          "type": "tv",     "icon": "📺"},
    # France — beIN + Canal+
    "beINSports1.qa@France":        {"broadcaster": "beIN Sports",       "country": "France",               "channels": "beIN Sports 1",                   "type": "tv",     "icon": "📺"},
    "beINSports2.qa@France":        {"broadcaster": "beIN Sports",       "country": "France",               "channels": "beIN Sports 2",                   "type": "tv",     "icon": "📺"},
    "beINSports3.qa@France":        {"broadcaster": "beIN Sports",       "country": "France",               "channels": "beIN Sports 3",                   "type": "tv",     "icon": "📺"},
    "CanalPlusSport.fr@SD":         {"broadcaster": "Canal+",            "country": "France",               "channels": "Canal+ Sport",                    "type": "tv",     "icon": "📺"},
    "CanalPlusSport2.fr@SD":        {"broadcaster": "Canal+",            "country": "France",               "channels": "Canal+ Sport 2",                  "type": "tv",     "icon": "📺"},
    # Africa — SuperSport
    "SuperSportPremierLeague.za@DStv": {"broadcaster": "SuperSport",     "country": "Sub-Saharan Africa",   "channels": "SuperSport Premier League (DStv #203)", "type": "tv", "icon": "📺"},
    "SuperSportFootball.za@DStv":   {"broadcaster": "SuperSport",        "country": "Sub-Saharan Africa",   "channels": "SuperSport Football (DStv #205)", "type": "tv",     "icon": "📺"},
    "SuperSportVariety1.za@DStv":   {"broadcaster": "SuperSport",        "country": "Sub-Saharan Africa",   "channels": "SuperSport Variety 1 (DStv #218)","type": "tv",     "icon": "📺"},
    # Malaysia — Astro
    "AstroSuperSport2.my@Astro":    {"broadcaster": "Astro",             "country": "Malaysia",             "channels": "Astro SuperSport 2",              "type": "tv",     "icon": "📺"},
    "AstroSuperSport3.my@Astro":    {"broadcaster": "Astro",             "country": "Malaysia",             "channels": "Astro SuperSport 3",              "type": "tv",     "icon": "📺"},
    "AstroSuperSport4.my@Astro":    {"broadcaster": "Astro",             "country": "Malaysia",             "channels": "Astro SuperSport 4",              "type": "tv",     "icon": "📺"},
    # Australia — Fox Sports / Stan
    "FoxSports503.au@Foxtel":       {"broadcaster": "Foxtel",            "country": "Australia",            "channels": "Fox Sports 503",                  "type": "tv",     "icon": "📺"},
    "FoxSports504.au@Foxtel":       {"broadcaster": "Foxtel",            "country": "Australia",            "channels": "Fox Sports 504",                  "type": "tv",     "icon": "📺"},
    "FoxSports505.au@Foxtel":       {"broadcaster": "Foxtel",            "country": "Australia",            "channels": "Fox Sports 505",                  "type": "tv",     "icon": "📺"},
    # Germany — Sky
    "SkySportPremierLeague.de@HD":  {"broadcaster": "Sky Deutschland",   "country": "Germany",              "channels": "Sky Sport Premier League HD",     "type": "tv",     "icon": "📺"},
    "SkySportUEFA1.de@HD":          {"broadcaster": "Sky Deutschland",   "country": "Germany",              "channels": "Sky Sport UEFA Champions League 1","type": "tv",    "icon": "📺"},
    # Italy — Sky
    "SkySportUno.it@HD":            {"broadcaster": "Sky Italia",        "country": "Italy",                "channels": "Sky Sport Uno",                   "type": "tv",     "icon": "📺"},
    "SkySportFootball.it@HD":       {"broadcaster": "Sky Italia",        "country": "Italy",                "channels": "Sky Sport Football",              "type": "tv",     "icon": "📺"},
    # India — Star Sports / Hotstar
    "StarSportsSelectHD1.in@Hotstar": {"broadcaster": "JioStar / StarSports", "country": "India / South Asia", "channels": "Star Sports Select HD1 · JioHotstar", "type": "tv", "icon": "📺"},
    "StarSportsSelectHD2.in@Hotstar": {"broadcaster": "JioStar / StarSports", "country": "India / South Asia", "channels": "Star Sports Select HD2 · JioHotstar", "type": "tv", "icon": "📺"},
}

# Football keywords to identify EPL/UCL programmes in EPG titles
EPL_KEYWORDS = [
    "premier league", "epl", "man utd", "manchester united", "manchester city",
    "arsenal", "liverpool", "chelsea", "spurs", "tottenham", "everton",
    "aston villa", "west ham", "newcastle", "brighton", "brentford",
    "crystal palace", "fulham", "bournemouth", "nottingham forest",
    "burnley", "sunderland", "leeds", "wolves", "wolverhampton",
]

UCL_KEYWORDS = [
    "champions league", "ucl", "uefa champions",
    "psg", "paris saint-germain", "barcelona", "real madrid",
    "atletico madrid", "atlético madrid", "atletico",
    "sporting cp", "sporting lisbon", "sporting portugal",
    "bayern munich", "bayern",
]

# Regex patterns to extract team names from EPG titles
# Handles: "Premier League: Arsenal v Bournemouth"
#          "PL: Man Utd vs Leeds Live"
#          "Football: Liverpool v Fulham"
#          "TNT Sports: UCL Arsenal v Sporting CP"
TITLE_PATTERNS = [
    # "Team1 v/vs Team2" — most common
    re.compile(
        r"(?:premier league|pl|champions league|ucl|football|soccer)[:\s]+(.+?)\s+(?:v|vs\.?)\s+(.+?)(?:\s+live|\s+\(live\)|\s+hd|\s+highlights)?$",
        re.IGNORECASE
    ),
    # Standalone "Team1 v Team2 Live"
    re.compile(
        r"^(.+?)\s+(?:v|vs\.?)\s+(.+?)(?:\s+live|\s+\(live\)|\s+hd|\s+highlights)?$",
        re.IGNORECASE
    ),
]


def _parse_xmltv_time(time_str: str) -> Optional[datetime]:
    """
    Parse XMLTV time format: "20260411113000 +0000" or "20260411123000 +0100"
    Returns UTC datetime.
    """
    try:
        # Split into timestamp and offset
        parts = time_str.strip().split()
        ts = parts[0]  # "20260411113000"
        offset_str = parts[1] if len(parts) > 1 else "+0000"

        dt = datetime.strptime(ts, "%Y%m%d%H%M%S")

        # Parse offset
        sign = 1 if offset_str[0] == "+" else -1
        oh = int(offset_str[1:3])
        om = int(offset_str[3:5])
        offset = timedelta(hours=oh, minutes=om) * sign

        dt_utc = dt - offset
        return dt_utc.replace(tzinfo=timezone.utc)
    except Exception as e:
        logger.debug(f"Failed to parse XMLTV time '{time_str}': {e}")
        return None


def _extract_teams(title: str) -> Optional[tuple]:
    """
    Extract (home_team, away_team) from an EPG programme title.
    Returns None if no match found.
    """
    # Try each pattern
    for pattern in TITLE_PATTERNS:
        m = pattern.match(title.strip())
        if m:
            home = m.group(1).strip().rstrip(":")
            away = m.group(2).strip()
            # Filter out obvious non-team strings
            if len(home) < 2 or len(away) < 2:
                continue
            if any(c.isdigit() for c in home) or any(c.isdigit() for c in away):
                continue
            return home, away

    return None


def _is_football(title: str, description: str = "") -> tuple:
    """
    Check if a programme is EPL or UCL football.
    Returns ("EPL"|"UCL"|None, title)
    """
    text = (title + " " + description).lower()

    # UCL takes priority
    if any(kw in text for kw in UCL_KEYWORDS):
        return "UCL", title

    # EPL
    if any(kw in text for kw in EPL_KEYWORDS):
        return "EPL", title

    return None, title


def _normalise_team(name: str) -> str:
    """Normalise team name for matching."""
    aliases = {
        "man utd": "manchester united",
        "man united": "manchester united",
        "man city": "manchester city",
        "spurs": "tottenham hotspur",
        "tottenham": "tottenham hotspur",
        "wolves": "wolverhampton wanderers",
        "wolverhampton": "wolverhampton wanderers",
        "newcastle": "newcastle united",
        "leeds": "leeds united",
        "psg": "paris saint-germain",
        "atletico": "atlético madrid",
        "atletico madrid": "atlético madrid",
        "sporting": "sporting cp",
        "sporting lisbon": "sporting cp",
        "sporting portugal": "sporting cp",
        "bayern": "bayern munich",
        "bournemouth": "afc bournemouth",
        "nott'm forest": "nottingham forest",
        "nottm forest": "nottingham forest",
        "brighton": "brighton",
        "brighton & hove albion": "brighton",
    }
    n = (name.strip().lower()
             .replace("&", "and")
             .replace(".", "")
             .replace("'", "")
             .replace("-", " "))
    return aliases.get(n, n)


def _make_fixture_key(home: str, away: str) -> str:
    return f"{_normalise_team(home)} v {_normalise_team(away)}"


def parse_guide(
    guide_path: str,
    days_ahead: int = 30,
) -> dict:
    """
    Parse an XMLTV guide.xml file and extract football fixtures.

    Returns dict:
    {
        fixture_key: {
            "home": str,
            "away": str,
            "competition": "EPL"|"UCL",
            "date": "YYYY-MM-DD",
            "kickoff_utc": "YYYY-MM-DDTHH:MM:SSZ",
            "broadcasters": [
                {
                    "broadcaster": str,
                    "country": str,
                    "channels": str,
                    "type": "tv"|"stream"|"free",
                    "icon": str,
                    "coverageType": "LIVE"|"HIGHLIGHTS",
                    "coverageStart": str|None,  # UTC ISO when broadcast begins
                }
            ]
        }
    }
    """
    try:
        tree = ET.parse(guide_path)
        root = tree.getroot()
    except FileNotFoundError:
        logger.warning(f"guide.xml not found at {guide_path} — EPG data skipped")
        return {}
    except ET.ParseError as e:
        logger.error(f"Failed to parse guide.xml: {e}")
        return {}

    today = date.today()
    cutoff = today + timedelta(days=days_ahead)

    # Build channel lookup: xmltv_id → channel metadata
    channels = {}
    for ch in root.findall("channel"):
        ch_id = ch.get("id", "")
        name = ch.findtext("display-name", "")
        channels[ch_id] = name

    results = {}  # fixture_key → { fixture data + broadcasters list }

    programmes = root.findall("programme")
    logger.info(f"Found {len(programmes)} programmes in guide.xml")

    football_count = 0

    for prog in programmes:
        channel_id = prog.get("channel", "")
        start_str = prog.get("start", "")
        stop_str = prog.get("stop", "")
        title = prog.findtext("title", "")
        desc = prog.findtext("desc", "") or ""
        category = prog.findtext("category", "") or ""

        # Only process sport/football categories or anything that might be football
        if title is None:
            continue

        # Check if this is football
        competition, _ = _is_football(title, desc + " " + category)
        if not competition:
            continue

        football_count += 1

        # Parse timing
        start_dt = _parse_xmltv_time(start_str)
        stop_dt = _parse_xmltv_time(stop_str)
        if not start_dt:
            continue

        # Filter to date window
        prog_date = start_dt.date()
        if prog_date < today or prog_date > cutoff:
            continue

        # Extract teams
        teams = _extract_teams(title)
        if not teams:
            # Try description
            teams = _extract_teams(desc[:100])
        if not teams:
            logger.debug(f"Could not extract teams from: '{title}'")
            continue

        home, away = teams
        fixture_key = _make_fixture_key(home, away)
        kickoff_utc = start_dt.strftime("%Y-%m-%dT%H:%M:%SZ")
        date_str = start_dt.strftime("%Y-%m-%d")

        # Look up channel metadata
        ch_meta = CHANNEL_MAP.get(channel_id)
        if not ch_meta:
            # Try partial match on channel_id
            for known_id, meta in CHANNEL_MAP.items():
                if known_id.split(".")[0].lower() in channel_id.lower():
                    ch_meta = meta
                    break

        if not ch_meta:
            logger.debug(f"Unknown channel: {channel_id} — skipping")
            continue

        # Determine coverage type
        is_highlights = (
            ch_meta.get("highlights_only", False) or
            "highlight" in title.lower() or
            "motd" in title.lower() or
            "match of the day" in title.lower() or
            "review" in title.lower()
        )
        coverage_type = "HIGHLIGHTS" if is_highlights else "LIVE"

        # Build broadcaster entry
        broadcaster_entry = {
            "broadcaster":   ch_meta["broadcaster"],
            "country":       ch_meta["country"],
            "region":        _get_region(ch_meta["country"]),
            "channels":      ch_meta["channels"],
            "type":          ch_meta["type"],
            "icon":          ch_meta["icon"],
            "coverageType":  coverage_type,
            "coverageStart": start_dt.strftime("%Y-%m-%dT%H:%M:%SZ"),
        }

        # Add or update fixture entry
        if fixture_key not in results:
            results[fixture_key] = {
                "home":        home,
                "away":        away,
                "competition": competition,
                "date":        date_str,
                "kickoff_utc": kickoff_utc,
                "broadcasters": [],
                "_title":      title,
            }
        else:
            # Use earliest start time as kick-off
            existing_ko = results[fixture_key]["kickoff_utc"]
            if kickoff_utc < existing_ko:
                results[fixture_key]["kickoff_utc"] = kickoff_utc
                results[fixture_key]["date"] = date_str

        # Avoid duplicate broadcaster entries for same channel
        existing_broadcasters = results[fixture_key]["broadcasters"]
        already_has = any(
            b["broadcaster"] == broadcaster_entry["broadcaster"] and
            b["country"] == broadcaster_entry["country"] and
            b["channels"] == broadcaster_entry["channels"]
            for b in existing_broadcasters
        )
        if not already_has:
            existing_broadcasters.append(broadcaster_entry)

    logger.info(
        f"EPG parse complete: {football_count} football programmes found, "
        f"{len(results)} unique fixtures extracted"
    )
    return results


def _get_region(country: str) -> str:
    """Map country to display region."""
    region_map = {
        "United Kingdom":               "🇬🇧 United Kingdom",
        "Republic of Ireland":          "🇮🇪 Republic of Ireland",
        "France":                       "🇪🇺 Europe",
        "Germany":                      "🇪🇺 Europe",
        "Italy":                        "🇪🇺 Europe",
        "Spain":                        "🇪🇺 Europe",
        "Netherlands":                  "🇪🇺 Europe",
        "Portugal":                     "🇪🇺 Europe",
        "Middle East & North Africa":   "🌍 Middle East & North Africa",
        "Sub-Saharan Africa":           "🌍 Sub-Saharan Africa",
        "India / South Asia":           "🇮🇳 India / South Asia",
        "Malaysia":                     "🌏 Asia",
        "Australia":                    "🇦🇺 Australia / New Zealand",
        "United States":                "🇺🇸 United States",
        "Canada":                       "🇨🇦 Canada",
    }
    return region_map.get(country, f"🌐 {country}")


if __name__ == "__main__":
    import sys
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    guide_path = sys.argv[1] if len(sys.argv) > 1 else "guide.xml"
    fixtures = parse_guide(guide_path, days_ahead=30)

    print(f"\nExtracted {len(fixtures)} fixtures from EPG:")
    for key, fx in sorted(fixtures.items(), key=lambda x: x[1]["date"]):
        print(f"\n  {fx['date']} {fx['kickoff_utc'][11:16]}  "
              f"{fx['home']} v {fx['away']}  [{fx['competition']}]")
        for b in fx["broadcasters"]:
            print(f"    {b['country']}: {b['broadcaster']} → {b['channels']} [{b['coverageType']}]")
